version: "3.5"
services:
    mysql-db:
        image: mysql
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - mysql-network
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - mysql-network
volumes:
    mysql-data:
networks:
    mysql-network:
        driver: bridge
        name: mysql-network