version: "3"
services:
    mysql-db:
        image: mysql
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    mysql-data: